
[Text]
FontFace=#Font#
FontSize=#MainFontSize#
FontColor=#ThemeSecondary#
StringEffect=Border
FontEffectColor=0,0,0,120
;FontColor=107,168,13
StringAlign=Left
Antialias=1

[WeatherText]
FontFace=#Font#
FontSize=#WeatherFontSize#
FontColor=#ThemeSecondary#
;FontColor=107,168,13
StringAlign=Left
Antialias=1

[TaskbarText]
FontFace=#Font#
FontSize=#SysTaskbarFontSize#
FontColor=#ThemeSecondary#
;FontColor=107,168,13
StringAlign=Left
Antialias=1

[ProgTaskbarText]
FontFace=#Font#
FontSize=#ProgTaskbarFontSize#
FontColor=#ThemeSecondary#
;FontColor=107,168,13
StringAlign=Left
Antialias=1

[Config]
FontFace=#Font#
FontSize=15
FontColor=#ThemeSecondary#
StringEffect=Border
FontEffectColor=0,0,0,120
;FontColor=107,168,13
StringAlign=Left
Antialias=1



















