[Variables]
;                                ; 
;           Rainmeter            ; 
;                                ;

;It is HIGHLY recommended to not touch these.
HWelcome=0
HBackground=1
HConfig=1
HTheme=1
HRes=1
HTask=1
HSysTask=1
HProgTask=1
HProgTaskList=1
HMenu=1
HClock=1
HEmail=1
HStorage=1
HWeather=1
HCredits=1
HDonate=1
HMisc=1
HRequired=1

;Just the font that will be used for items in this skin.
Font=Century Gothic

;Main values that make the skin function.
ScreenWidth=1920
ScreenHeight=1080
MainFontSize=15
WeatherFontSize=12

;The skin's main color scheme.
;Green - 107,168,13
;Red - 164,29,46
;Blue - 9,170,180
;Orange - 162,58,27
Theme=107,168,13

;The skin's secondary color scheme.
;Silver - 182,182,182
ThemeSecondary=182,182,182

;Overall color.
BGColor=Green

;                                ; 
;             Drives             ; 
;                                ;

;This is your primary drive, just put the letter of the drive here. For example, if I put 'C' here, it will show as the C:\ Drive. This option is here incase you want to change the orientation of where the core is placed in the HDD dropdown menu.
DriveLetterOne=C

;This is your secondary drive, just put the letter of the drive here. For example, if I put 'E' here, it will show as the E:\ Drive. This option is here incase you want to change the orientation of where the core is placed in the HDD dropdown menu.
DriveLetterTwo=E

;                                ; 
;             Network            ; 
;                                ;

;Minimum net in that you want to be recognized by the skin, measured in bits.
MinNetIn=0

;Maximum net total that you want to be recognized by the skin, measured in bits.
MaxNetIn=26500000

;Minimum net out that you want to be recognized by the skin, measured in bits.
MinNetOut=0

;Maximum net total that you want to be recognized by the skin, measured in bits.
MaxNetOut=26500000

;                                ; 
;             Weather            ; 
;                                ;

;This is your weather location code, it is used to get the correct weather info for your region. To get your weather code, go to this website and type in the city or town nearest you: http://edg3.co.uk/snippets/weather-location-codes/
LocationCode=USGA0552

;For fahrenheit, put 'F'
;For celcius, put 'M'
TempUnit=F

;The resolution and color of the button that changes days for the weather app.
ButtonResolution=1920x1080
ButtonColor=Green

;                                ; 
;             Email              ; 
;                                ;

;This is where your gmail account login info goes. It allows the skin to show how many new emails there are in the account.
Username=Username
Password=Password

MaxEmailCount=25

;                                ; 
;          Recycle Bin           ; 
;                                ;

;Minimum recycle bin size that you want to be recognized by the skin, measured in bytes. Here is a conversion calculater so you can change the value if so desired: http://www.convertunits.com/from/GB/to/byte
MinRecycleBinSize=0

;Maximum recycle bin size that you want to be recognized by the skin, measured in bytes. Here is a conversion calculater so you can change the value if so desired: http://www.convertunits.com/from/GB/to/byte
MaxRecycleBinSize=1073741824

;                                ; 
;             Clock              ; 
;                                ;

;For a 12 hour clock mode, put 'I'
;For a 24 hour clock mode, put 'H'
ClockMode=I

;                                ; 
;            Taskbar             ; 
;                                ;

;What time the taskbar will use.
SysTask=TwelveSystem.ini
ProgTask=TwelveProgram.ini

;System taskbar size.
SysTaskbarHeight=30
SysTaskbarWidth=1680
SysTaskbarFontSize=11

;Program taskbar size.
ProgTaskbarHeight=35
ProgTaskbarWidth=1920
ProgTaskbarFontSize=12

;Program names and paths
Prog1=Steam
Prog1Path=E:\Program Files (x86)\Steam\Steam.exe

Prog2=PhotoShop
Prog2Path="C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe"

Prog3=Sublime Text 2
Prog3Path="C:\Program Files (x86)\Sublime Text 2\sublime_text.exe"

Prog4=Skype
Prog4Path="C:\Program Files (x86)\Skype\Phone\Skype.exe"

Prog5=Rainmeter
Prog5Path="C:\Program Files\Rainmeter\Rainmeter.exe"


Prog6=PhotoShop
Prog6Path="C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe"
   
  
Button=1920x1080
