[Variables]
;                                ; 
;           Rainmeter            ; 
;                                ;

;It is HIGHLY recommended to not touch these.
HWelcome=0
HBackground=1
HConfig=1
HTheme=1
HRes=1
HTask=1
HSysTask=1
HProgTask=1
HProgTaskList=1
HMenu=1
HClock=1
HEmail=1
HStorage=1
HWeather=1
HCredits=1
HDonate=1
HMisc=1
HRequired=1

;Just the font that will be used for items in this skin.
Font=Century Gothic

;Main values that make the skin function.
ScreenWidth=1920
ScreenHeight=1080
MainFontSize=15
WeatherFontSize=12






CpuModuleFontSize=18
CpuModuleFontColor=182,182,182






;The skin's main color scheme.
;Green - 107,168,13
;Red - 177,10,29
;Cyan - 9,170,180
;Blue - 14,107,189
;Orange - 162,58,27
Theme=107,168,13

;The skin's secondary color scheme.
;Silver - 182,182,182
ThemeSecondary=182,182,182

BGColor=Green
;                                ; 
;             Drives             ; 
;                                ;

;This is your primary drive, just put the letter of the drive here. For example, if I put 'C' here, it will show as the C:\ Drive. This option is here in case you want to change the orientation of where the core is placed in the HDD dropdown menu.
DriveLetterOne=C

;This is your secondary drive, just put the letter of the drive here. For example, if I put 'E' here, it will show as the E:\ Drive. This option is here in case you want to change the orientation of where the core is placed in the HDD dropdown menu.
DriveLetterTwo=E

;                                ; 
;           SWAP Value           ; 
;                                ;

;Maximum SWAP size that you want to be recognized by the skin, measured in bytes. Here is a conversion calculator so you can change the value if so desired: http://www.convertunits.com/from/GB/to/byte
;Default value is 2 GB
SWAPMaxValue=2147483648


;                                ; 
;             Network            ; 
;                                ;

;Minimum net in that you want to be recognized by the skin, measured in bits.
;Default value is 0
MinNetIn=0

;Maximum net total that you want to be recognized by the skin, measured in bits.
;Default value is 26500000
MaxNetIn=26500000

;Minimum net out that you want to be recognized by the skin, measured in bits.
;Default value is 0
MinNetOut=0

;Maximum net total that you want to be recognized by the skin, measured in bits.
;Default value is 26500000
MaxNetOut=26500000

;                                ; 
;             Weather            ; 
;                                ;

;This is your weather location code, it is used to get the correct weather info for your region. To get your weather code, go to this website and type in the city or town nearest you: http://edg3.co.uk/snippets/weather-location-codes/
LocationCode=USGA0552

;For fahrenheit, put 'F'
;For celcius, put 'M'
TempUnit=F

;The resolution and color of the button that changes days for the weather app.
ButtonResolution=1920x1080
ButtonColor=Green

;                                ; 
;             Email              ; 
;                                ;

;This is where your gmail account login info goes. It allows the skin to show how many new emails there are in the account.
Username=Username
Password=Password

;Default value is 25
MaxEmailCount=25

;                                ; 
;          Recycle Bin           ; 
;                                ;

;Minimum recycle bin size that you want to be recognized by the skin, measured in bytes. Here is a conversion calculator so you can change the value if so desired: http://www.convertunits.com/from/GB/to/byte
;Default value is 0 GB
MinRecycleBinSize=0

;Maximum recycle bin size that you want to be recognized by the skin, measured in bytes. Here is a conversion calculator so you can change the value if so desired: http://www.convertunits.com/from/GB/to/byte
;Default value is 1 GB
MaxRecycleBinSize=1073741824

;                                ; 
;             Clock              ; 
;                                ;

;For a 12 hour clock mode, put 'I'
;For a 24 hour clock mode, put 'H'
;Default value is "I", or 12 hour mode.
ClockMode=I

;                                ; 
;            Taskbar             ; 
;                                ;

;What time the taskbar will use.
SysTask=TwelveSystem.ini
ProgTask=TwelveProgram.ini

;System taskbar size.
SysTaskbarHeight=35
SysTaskbarWidth=1920
SysTaskbarFontSize=12

;Program taskbar size.
ProgTaskbarHeight=35
ProgTaskbarWidth=1920
ProgTaskbarFontSize=12

;Program names and paths
Prog1=Steam
Prog1Path=E:\Program Files (x86)\Steam\Steam.exe

Prog2=PhotoShop
Prog2Path="C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe"

Prog3=Sublime Text 2
Prog3Path="C:\Program Files (x86)\Sublime Text 2\sublime_text.exe"

Prog4=Skype
Prog4Path="C:\Program Files (x86)\Skype\Phone\Skype.exe"

Prog5=Rainmeter
Prog5Path="C:\Program Files\Rainmeter\Rainmeter.exe"


Prog6=PhotoShop
Prog6Path="C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe"
Button=1920x1080
